catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('movies/', views.MovieListView.as_view(), name='movies'),
    path('movie/<int:pk>', views.MovieDetailView.as_view(), name='movie-detail'),
    path('directors/', views.DirectorListView.as_view(), name='directors'),
    path('director/<int:pk>',
         views.DirectorDetailView.as_view(), name='director-detail'),
]


urlpatterns += [
    path('mymovies/', views.LoanedMoviesByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedMoviesAllListView.as_view(), name='all-borrowed'),
]


# Add URLConf for employer to renew a movie.
urlpatterns += [
    path('movie/<uuid:pk>/renew/', views.renew_movie_employer, name='renew-movie-employer'),
]


# Add URLConf to create, update, and delete directors
urlpatterns += [
    path('director/create/', views.DirectorCreate.as_view(), name='director-create'),
    path('director/<int:pk>/update/', views.DirectorUpdate.as_view(), name='director-update'),
    path('director/<int:pk>/delete/', views.DirectorDelete.as_view(), name='director-delete'),
]

# Add URLConf to create, update, and delete movies
urlpatterns += [
    path('movie/create/', views.MovieCreate.as_view(), name='movie-create'),
    path('movie/<int:pk>/update/', views.MovieUpdate.as_view(), name='movie-update'),
    path('movie/<int:pk>/delete/', views.MovieDelete.as_view(), name='movie-delete'),
]

moviegallery/urls.py
from django.urls import path
from django.contrib import admin

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]



#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Genre(models.Model):
    """Model representing a movie genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        help_text="Enter a movie genre (e.g. Science Fiction, etc.)"
        )

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Country(models.Model):
    """Model representing a Country (e.g. USA, France, Japan, etc.)"""
    name = models.CharField(max_length=200,
                            help_text="Enter the country of production of the movie (e.g. USA, France, Japan, etc.)")

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Movie(models.Model):
    """Model representing a movie (but not a specific copy of a movie)."""
    title = models.CharField(max_length=200)
    director = models.ForeignKey('Director', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because movie can only have one director, but directors can have multiple movies
    # Director as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the movie")
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this movie")
    # ManyToManyField used because a genre can contain many movies and a Movie can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    #country = models.ForeignKey('Country', on_delete=models.SET_NULL, null=True)
    country = models.ForeignKey('Country', on_delete=models.SET_NULL, null=True)
    
    class Meta:
        ordering = ['title', 'director']

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular movie instance."""
        return reverse('movie-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


import uuid  # Required for unique movie instances
from datetime import date

from django.contrib.auth.models import User  # Required to assign User as a borrower


class MovieInstance(models.Model):
    """Model representing a specific copy of a disk (i.e. that can be borrowed)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular movie(disk)")
    movie = models.ForeignKey('Movie', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Disk availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set disk as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return '{0} ({1})'.format(self.id, self.movie.title)


class Director(models.Model):
    """Model representing an director."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']
        
        permissions = (("can_mark_returned", "Set disk as returned"),)

    def get_absolute_url(self):
        """Returns the url to access a particular director instance."""
        return reverse('director-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.last_name, self.first_name)

catalog/forms.py
from django import forms

import logging

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.

logger = logging.getLogger(__name__)

class RenewMovieForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Проверка того, что дата не выходит за "нижнюю" границу (не в прошлом).
        if data < datetime.date.today():
            logger.error("Invalid date")
            raise ValidationError(_('Invalid date - renewal in past'))

        #Проверка того, то дата не выходит за "верхнюю" границу (+4 недели).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            logger.error("Invalid date")
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
from django.shortcuts import render
import asyncio
import logging
from time import sleep
from threading import Thread
# Create your views here.
import threading

from .models import Movie, Director, MovieInstance, Genre

from django.conf import settings
from django.core.mail import send_mail


logger = logging.getLogger(__name__)

def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_movies = Movie.objects.all().count()
    num_instances = MovieInstance.objects.all().count()
    # Available copies of movies
    num_instances_available = MovieInstance.objects.filter(status__exact='a').count()
    num_directors = Director.objects.count()  # The 'all()' is implied by default.

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits+1

    logger.info("Visit home page")

    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_movies': num_movies, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available, 'num_directors': num_directors,
                 'num_visits': num_visits},
    )


from django.views import generic


class MovieListView(generic.ListView):
    """Generic class-based view for a list of Movies."""
    model = Movie
    paginate_by = 10


class MovieDetailView(generic.DetailView):
    """Generic class-based detail view for a movie."""
    model = Movie


class DirectorListView(generic.ListView):
    """Generic class-based list view for a list of directors."""
    model = Director
    paginate_by = 10


class DirectorDetailView(generic.DetailView):
    """Generic class-based detail view for an director."""
    model = Director


from django.contrib.auth.mixins import LoginRequiredMixin


class LoanedMoviesByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing movies on loan to current user."""
    model = MovieInstance
    template_name = 'catalog/movieinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        logger.info("Movies on loan")
        return MovieInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


from django.contrib.auth.mixins import PermissionRequiredMixin


class LoanedMoviesAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all movies on loan. Only visible to users with can_mark_returned permission."""
    model = MovieInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/movieinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        logger.info("Movies on loan")
        #return MovieInstance.objects.filter(status__exact='o').order_by('due_back')
        return MovieInstance.objects.select_related("movie").order_by('due_back')


from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.contrib.auth.decorators import login_required, permission_required

# from .forms import RenewMovieForm
from catalog.forms import RenewMovieForm


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_movie_employer(request, pk):
    """View function for renewing a specific MovieInstance by employer."""
    movie_instance = get_object_or_404(MovieInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewMovieForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            movie_instance.due_back = form.cleaned_data['renewal_date']
            movie_instance.save()

            # redirect to a new URL:
            logger.info("Renew movie")
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form
    else:
        logger.warning("Create the default form")
        
        thread = threading.Thread(target=send_mail, args=(
            'Django mail',
            'This e-mail was sent with Django. Something wrong with movie form',
            'alyonazapetskaya@mail.ru',
            ['alyonazapetskaya@mail.ru']), kwargs={'fail_silently': False})
        thread.start()
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewMovieForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'movie_instance': movie_instance,
    }

    return render(request, 'catalog/movie_renew_employer.html', context)
    

def start_new_thread(function):
    def decorator(*args, **kwargs):
        t = Thread(target = function, args=args, kwargs=kwargs)
        t.daemon = True
        t.start()
    return decorator

async def renew_movie_employer_async(request, pk):
    """View function for renewing a specific MovieInstance by employer."""
    movie_instance = get_object_or_404(MovieInstance, pk=pk)

    await asyncio.sleep(3)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewMovieForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            movie_instance.due_back = form.cleaned_data['renewal_date']
            movie_instance.save()

            await asyncio.sleep(3)

            # redirect to a new URL:
            logger.info("Renew movie")
            return HttpResponseRedirect(reverse('all-borrowed'))

    # If this is a GET (or any other method) create the default form
    else:
        logger.warning("Create the default form")
        await asyncio.sleep(3)
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewMovieForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'movie_instance': movie_instance,
    }

    return render(request, 'catalog/movie_renew_employer.html', context)

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Director


class DirectorCreate(PermissionRequiredMixin, CreateView):
    model = Director
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': '11/05/2021'}
    permission_required = 'catalog.can_mark_returned'


class DirectorUpdate(PermissionRequiredMixin, UpdateView):
    model = Director
    fields = '__all__' 
    permission_required = 'catalog.can_mark_returned'


class DirectorDelete(PermissionRequiredMixin, DeleteView):
    model = Director
    success_url = reverse_lazy('directors')
    permission_required = 'catalog.can_mark_returned'


# Classes created for the forms challenge
class MovieCreate(PermissionRequiredMixin, CreateView):
    model = Movie
    fields = ['title', 'director', 'summary', 'isbn', 'genre', 'country']
    permission_required = 'catalog.can_mark_returned'


class MovieUpdate(PermissionRequiredMixin, UpdateView):
    model = Movie
    fields = ['title', 'director', 'summary', 'isbn', 'genre', 'country']
    permission_required = 'catalog.can_mark_returned'


class MovieDelete(PermissionRequiredMixin, DeleteView):
    model = Movie
    success_url = reverse_lazy('movies')
    permission_required = 'catalog.can_mark_returned'

catalog/templates/catalog/director_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Director</h1>

<p>Are you sure you want to delete the director: {{ director }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/director_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Director: {{ director }} </h1>
<p>{{director.date_of_birth}} - {% if director.date_of_death %}{{director.date_of_death}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Movies</h4>

<dl>
{% for movie in director.movie_set.all %}
  <dt><a href="{% url 'movie-detail' movie.pk %}">{{movie}}</a> ({{movie.movieinstance_set.all.count}})</dt>
  <dd>{{movie.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

catalog/templates/catalog/director_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

catalog/templates/catalog/director_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Director List</h1>

{% if director_list %}
  <ul>

  {% for director in director_list %}
    <li>
      <a href="{{ director.get_absolute_url }}">
      {{ director }} ({{director.date_of_birth}} - {% if director.date_of_death %}{{director.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no directors available.</p>
{% endif %}
        
        
        
{% endblock %}

catalog/templates/catalog/movie_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Movie</h1>

<p>Are you sure you want to delete the movie: {{ movie }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

catalog/templates/catalog/movie_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Title: {{ movie.title }}</h1>

<p><strong>Director:</strong> <a href="{{ movie.director.get_absolute_url }}">{{ movie.director }}</a></p>
<p><strong>Summary:</strong> {{ movie.summary }}</p>
<p><strong>ISBN:</strong> {{ movie.isbn }}</p> 
<p><strong>Country:</strong> {{ movie.country }}</p>  
<p><strong>Genre:</strong> {{ movie.genre.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Copies</h4>

{% for copy in movie.movieinstance_set.all %}
<hr>
<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
<p><strong>Imprint:</strong> {{copy.imprint}}</p>
<p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/movie_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

catalog/templates/catalog/movie_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Movie List</h1>

    {% if movie_list %}
    <ul>

      {% for movie in movie_list %}
      <li>
        <a href="{{ movie.get_absolute_url }}">{{ movie.title }}</a> ({{movie.director}})
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no movies in the gallery.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/movie_renew_employer.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{movie_instance.movie.title}}</h1>
    <p>Borrower: {{movie_instance.borrower}}</p>
    <p{% if movie_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{movie_instance.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/movie_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Renew: {{movie_instance.movie.title}}</h1>
    <p>Borrower: {{movie_instance.borrower}}</p>
    <p{% if movie_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{movie_instance.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

catalog/templates/catalog/movieinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Disks</h1>

    {% if movieinstance_list %}
    <ul>

      {% for movieinst in movieinstance_list %} 
      <li class="{% if movieinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'movie-detail' movieinst.movie.pk %}">{{movieinst.movie.title}}</a> ({{ movieinst.due_back }}) {% if user.is_staff %}- {{ movieinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-movie-employer' movieinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no disks borrowed.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/movieinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed disks</h1>

    {% if movieinstance_list %}
    <ul>

      {% for movieinst in movieinstance_list %} 
      <li class="{% if movieinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'movie-detail' movieinst.movie.pk %}">{{movieinst.movie.title}}</a> ({{ movieinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no disks borrowed.</p>
    {% endif %}       
{% endblock %}